In [ ]:
import pandas as pd
data = { 'apples':[3, 2, 0, 1], 'oranges':[0, 3, 7, 2] }
df = pd.DataFrame(data)
df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [ ]:
import pandas as pd
data = {'id':[1, 2, 3, 4], 'name':['John', 'Alice', 'Bob', 'Lorgan'], 'branch':['cse', 'csit', 'ece', 'ai'], 'section':[2, 2, 3, 3]}
df = pd.DataFrame(data)
df

   id    name branch  section
0   1    John    cse        2
1   2   Alice   csit        2
2   3     Bob    ece        3
3   4  Lorgan     ai        3

In [ ]:
import pandas as pd
data = {'id':[1, 2, 3, 4], 'name':['John', 'Alice', 'Bob', 'Lorgan'], 'branch':['cse', 'csit', 'ece', 'ai'], 'section':[2, 2, 3, 3]}
df = pd.DataFrame(data, index=['02', '03', '04', '05'])
df

    id    name branch  section
02   1    John    cse        2
03   2   Alice   csit        2
04   3     Bob    ece        3
05   4  Lorgan     ai        3

In [ ]:
import pandas as pd
data = {'id':[1, 2, 3, 4], 'name':['John', 'Alice', 'Bob', 'Lorgan'], 'branch':['cse', 'csit', 'ece', 'ai'], 'section':[2, 2, 3, 3]}
df = pd.DataFrame(data, index=['02', '03', '04', '05'])
df.loc['02']

id            1
name       John
branch      cse
section       2
Name: 02, dtype: object

In [ ]:
import pandas as pd
df=pd.read_csv('tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
import pandas as pd
df=pd.read_csv('tips.csv',index_col=0)
df

,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
total_bill,,,,,,,,,,
16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
import pandas as pd
data = { 'apples':[3, 2, 0, 1], 'oranges':[0, 3, 7, 2] }
df = pd.DataFrame(data)
df.to_csv('new_dataset.csv')
df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [ ]:
import pandas as pd
data = { 'apples':[3, 2, 0, 1], 'oranges':[0, 3, 7, 2] }
df = pd.DataFrame(data)
df.to_json('new_dataset.json')
df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [ ]:
movies_df = pd.read_csv("movies.csv.zip", index_col="title")
movies_df

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,director
title,,,,,,,,,,,,,,,,,,,,,
Avatar,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
Pirates of the Caribbean: At World's End,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
Spectre,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
The Dark Knight Rises,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
John Carter,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
El Mariachi,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
Newlyweds,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
"Signed, Sealed, Delivered",4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
Shanghai Calling,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
My Date with Drew,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
movies_df.head(1)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,director
title,,,,,,,,,,,,,,,,,,,,,
Avatar,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron

In [ ]:
movies_df.tail(2)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,director
title,,,,,,,,,,,,,,,,,,,,,
Shanghai Calling,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
My Date with Drew,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4803 entries, Avatar to My Date with Drew
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  cast                  4760 non-null   object
 21  crew                  4803 non-null   object
 22  director              4773 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 1.0+ MB

In [ ]:
movies_df.shape

(4803, 23)

In [ ]:
movies_df = movies_df.drop_duplicates()
movies_df.shape

(4803, 23)

In [ ]:
df=pd.read_csv('tips.csv')
k=pd.concat([df,df])
k
k.shape
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [ ]:
movies_df.drop_duplicates(inplace=True)

### Adding a new column to `movies_df`

In [ ]:
import pandas as pd
miss = [{'a':1, 'b':2},{'a':5, 'b':10, 'c':20}]
df1 = pd.DataFrame(miss,index=['first','second'],columns=['a','b'])
df2 = pd.DataFrame(miss,index=['first','second'],columns=['a','b1'])
print(df1)
print('........')
print(df2)

        a   b
first   1   2
second  5  10
........
        a  b1
first   1 NaN
second  5 NaN

In [ ]:
df.dropna()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.fillna(0)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Date': ['2025-01-05', '05/01/2025', 'Jan 5, 2025', '2025.01.05']
})

df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

print(df)

         Date
0  2025-01-05
1         NaN
2         NaN
3         NaN

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'BOB', 'charlie', 'DAVID']
})

# Convert all names to lowercase
df['Name_lower'] = df['Name'].str.lower()
print(df)

# Convert all names to uppercase
df['Name_upper'] = df['Name'].str.upper()

print(df)

      Name Name_lower
0    Alice      alice
1      BOB        bob
2  charlie    charlie
3    DAVID      david
      Name Name_lower Name_upper
0    Alice      alice      ALICE
1      BOB        bob        BOB
2  charlie    charlie    CHARLIE
3    DAVID      david      DAVID

In [ ]:
iris_df = pd.read_csv('Iris.csv')

print("Original Iris DataFrame:")
display(iris_df.head())

iris_df['Species_lower'] = iris_df['Species'].str.lower()

iris_df['Species_upper'] = iris_df['Species'].str.upper()

print("\nIris DataFrame with lowercase and uppercase Species:")
display(iris_df[['Species', 'Species_lower', 'Species_upper']].head())

Original Iris DataFrame:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Iris DataFrame with lowercase and uppercase Species:

       Species Species_lower Species_upper
0  Iris-setosa   iris-setosa   IRIS-SETOSA
1  Iris-setosa   iris-setosa   IRIS-SETOSA
2  Iris-setosa   iris-setosa   IRIS-SETOSA
3  Iris-setosa   iris-setosa   IRIS-SETOSA
4  Iris-setosa   iris-setosa   IRIS-SETOSA

In [ ]:
import pandas as pd

movies_df = pd.read_csv("movies.csv.zip")

movies_df['title_lower'] = movies_df['title'].str.lower()

print(movies_df)

movies_df['title_upper'] = movies_df['title'].str.upper()

print(movies_df)

      index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

                                       spoken_languages    status  \
0     [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1              [{"iso_639_1": "en", "name": "English"}]  Released
2     [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3              [{"iso_639_1": "en", "name": "English"}]  Released
4              [{"iso_639_1": "en", "name": "English"}]  Released
...                                                 ...       ...
4798      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799                                                 []  Released
4800           [{"iso_639_1": "en", "name": "English"}]  Released
4801           [{"iso_639_1": "en", "name": "English"}]  Released
4802           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                         title  vote_average vote_count  \
0                                       Avatar           7.2      11800
1     Pirates of the Caribbean: At World's End           6.9       4500
2                                      Spectre           6.3       4466
3                        The Dark Knight Rises           7.6       9106
4                                  John Carter           6.1       2124
...                                        ...           ...        ...
4798                               El Mariachi           6.6        238
4799                                 Newlyweds           5.9          5
4800                 Signed, Sealed, Delivered           7.0          6
4801                          Shanghai Calling           5.7          7
4802                         My Date with Drew           6.3         16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director  \
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

                                   title_lower
0                                       avatar
1     pirates of the caribbean: at world's end
2                                      spectre
3                        the dark knight rises
4                                  john carter
...                                        ...
4798                               el mariachi
4799                                 newlyweds
4800                 signed, sealed, delivered
4801                          shanghai calling
4802                         my date with drew

[4803 rows x 25 columns]
      index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

        status                                            tagline  \
0     Released                        Enter the World of Pandora.
1     Released     At the end of the world, the adventure begins.
2     Released                              A Plan No One Escapes
3     Released                                    The Legend Ends
4     Released               Lost in our world, found in another.
...        ...                                                ...
4798  Released  He didn't come looking for trouble, but troubl...
4799  Released  A newlywed couple's honeymoon is upended by th...
4800  Released                                                NaN
4801  Released                           A New Yorker in Shanghai
4802  Released                                                NaN

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800
1     Pirates of the Caribbean: At World's End           6.9        4500
2                                      Spectre           6.3        4466
3                        The Dark Knight Rises           7.6        9106
4                                  John Carter           6.1        2124
...                                        ...           ...         ...
4798                               El Mariachi           6.6         238
4799                                 Newlyweds           5.9           5
4800                 Signed, Sealed, Delivered           7.0           6
4801                          Shanghai Calling           5.7           7
4802                         My Date with Drew           6.3          16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director  \
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

                                   title_lower  \
0                                       avatar
1     pirates of the caribbean: at world's end
2                                      spectre
3                        the dark knight rises
4                                  john carter
...                                        ...
4798                               el mariachi
4799                                 newlyweds
4800                 signed, sealed, delivered
4801                          shanghai calling
4802                         my date with drew

                                   title_upper
0                                       AVATAR
1     PIRATES OF THE CARIBBEAN: AT WORLD'S END
2                                      SPECTRE
3                        THE DARK KNIGHT RISES
4                                  JOHN CARTER
...                                        ...
4798                               EL MARIACHI
4799                                 NEWLYWEDS
4800                 SIGNED, SEALED, DELIVERED
4801                          SHANGHAI CALLING
4802                         MY DATE WITH DREW

[4803 rows x 26 columns]